name: CobraKits
main: us.drome.CobraKits.CobraKits
version: ${project.version}
author: TheAcademician
description: ${project.description}
website: ${project.url}

commands:
  ckits:
    description: A dynamic kit plugin completely configurble in-game!
    usage: /ckits help|current|cooldown|duration|silent|concat [value]
  ckit:
    permission: cobrakits.create
    permission-message: You do not have permission to create Kits.
    description: Create a kit based on your current inventory.
    usage: /ckit [kitname] -kc [itemID:amount] -cd [cooldown]
  lkit:
    description: List all of the available kits.
    usage: /lkit
    aliases: kits
  ukit:
    permission: cobrakits.update
    permission-message: You do not have permission to update Kits.
    description: Update a kit to your inventory.
    usage: /ukit [kitname] -kc [itemID:amount] -cd [cooldown]
  rkit:
    permission: cobrakits.rename
    permission-message: You do not have permission to rename Kits.
    description: Rename a kit.
    usage: /rkit [kitname] [newname]
  dkit:
    permission: cobrakits.delete
    permission-message: You do not have permission to delete Kits.
    description: Deletes the specificed kit.
    usage: /dkit [kitname]
  kit:
    description: Use the kit or Give it to someone else.
    usage: /kit [kitname] [targetplayer]

permissions:
  cobrakits.*:
    description: Give access to all CobraKits commands
    children:
      cobrakits.create: true
      cobrakits.createall: true
      cobrakits.update: true
      cobrakits.updateall: true
      cobrakits.rename: true
      cobrakits.renameall: true
      cobrakits.use: true
      cobrakits.useall: true
      cobrakits.delete: true
      cobrakits.deleteall: true
      cobrakits.give: true
      cobrakits.cooldown.bypass: true
      cobrakits.cost.bypass: true
      cobrakits.login: true
      cobrakits.respawn: true
  cobrakits.create:
    description: Allows player to create a kit
    default: op
  cobrakits.createall:
    children:
      cobrakits.create: true
    description: Allows player to create global kits.
    default: op
  cobrakits.update:
    description: Allows player to update an existing kit
    default: op
  cobrakits.updateall:
    children:
      cobrakits.update: true
    description: Allows player to update any kit.
    default: op
  cobrakits.rename:
    description: Allows a player to rename a kit.
    default: op
  cobrakits.renameall:
    children:
      cobrakits.rename: true
    description: Allows a player to rename any kit.
    default: op
  cobrakits.use:
    description: Allows player to use their kits
    default: op
  cobrakits.useall:
    children:
      cobrakits.use: true
    description: Allows player to use any kit
    default: op
  cobrakits.delete:
    description: Allows player to delete their kits
    default: op
  cobrakits.deleteall:
    children:
      cobrakits.delete: true
    description: Allows player to delete any kit
    default: op
  cobrakits.give:
    description: Allows player to give kits to other players.
    default: op
  cobrakits.cooldown.bypass:
    description: Allows the player to not be affected by kit cooldowns
    default: op
  cobrakits.cost.bypass:
    description: Players with this permission does not pay kit costs.
    default: op
  cobrakits.login:
    description: This permissions allows the player to receive all login kits.
    default: op
  cobrakits.respawn:
    description: This permission allows the player to receive all respawn kits.
    default: op
